apiVersion: v1
kind: Service
metadata:
  name: locust-gerador-senhas
spec:
  selector:
    app: locust-gerador-senhas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089
  type: ClusterIP
