apiVersion: v1
kind: Service
metadata:
  name: gerador-senhas
spec:
  selector:
    app: gerador-senhas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
