apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gerador-senhas
  name: gerador-senhas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gerador-senhas
  template:
    metadata:
      labels:
        app: gerador-senhas
    spec:
      containers:
      - image: carlos/gerador-senhas:1.0
        name: gerador-senhas
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
